name: Run Tests (Postman + Playwright)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Compile TypeScript
        run: npx tsc

      - name: Run API Tests (Newman)
        run: node dist/newman-runner.js

      - name: Run UI Tests (Playwright)
        run: npx playwright test

      - name: Upload API Report
        uses: actions/upload-artifact@v3
        with:
          name: postman-report
          path: reports/api/newman-report.html

      - name: Upload UI Report
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: reports/ui/
